### ISSUE TITLE
Request: Make "Verify your organization" Case Insensitive

### ISSUE THREAD

**Issue by Julian88Tex** [SalesforceFoundation/mrbelvedere#24]
When pasting in this form I sometimes use a mixed upper and lower case version of this username. Username is only validated true when case matches. It would be nice to have it validate true if text matches but case doesn't (i.e. case insensitive).

Example of error thrown when text matches but the case doesn't: https://www.dropbox.com/s/evp1pjqkgq1sx0e/Screenshot%202018-12-14%2010.33.33.png?dl=0

I believe the change would be around this line: https://github.com/SalesforceFoundation/mrbelvedere/blob/1fa84d3744f7504d224da3f2edfea7191d130653/mpinstaller/templates/mpinstaller/package_version_overview.html#L214

**Comment by cdcarter** [comment]
@Julian88Tex - thanks for the report. We're currently in the process of phasing out this repo, and launching our next generation installer tool. We're not going to do any new feature work on mrbelvedere, but I'll add this as a test case for https://github.com/SFDO-Tooling/Metadeploy
